name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # --all-targets:  check sources and tests
          # --all-features: check non-default crate features
          # -D warnings:    fail the build when encountering warnings
          args: --all-targets --all-features -- -D warnings
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Detect undefined behavior with Miri
        run: |
          cargo +nightly miri test
          cargo +nightly miri run
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
